import WindowProvider, { WindowContext } from "./context/WindowContext";
import "./globals.css";

export const metadata = {
  title: "MiwaBox Cloud",
  description: "Generated by Miwabox.live",
};
import "./styles/Nav/Menu.css";
import "./styles/Nav/MenuRes.css";
import "./styles/ShowPanel/Modal.css"
import "./styles/ShowPanel/ModalRes.css"
import "./styles/Login/Login.css"
import "./styles/Login/Login_Res.css"

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <WindowProvider>
        <body>{children}</body>
      </WindowProvider>
    </html>
  );
}